package com.leduc.staff.dataAccessLayer.Department;

public enum PositionTitle {
    LIBRARIAN,
    ASSISTANT_LIBRARIAN,
    ARCHIVIST,
    CATALOGUER,
    LIBRARY_TECHNICIAN,
    REFERENCE_LIBRARIAN,
    CHILDREN_LIBRARIAN,
    DIGITAL_RESOURCES_LIBRARIAN,
    LIBRARY_MANAGER,
    DIRECTOR
}
